In [2]:
import numpy as np
import Reduction
import Generador
import GeneticColor
import GeneticCubic
import Backtrack3Coloreable

In [3]:
_, g1 = Generador.ConnexGraphGenerator(6)

In [4]:
g1

array([[0, 1, 0, 0, 1, 1],
       [1, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 1],
       [0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0]])

In [5]:
is_coloreable = GeneticColor.genetic_coloro(g1)

Generation:  500 Best_Fitness:  1 Individual:  [3, 2, 3, 3, 1, 1]
Generation:  1000 Best_Fitness:  1 Individual:  [3, 2, 3, 2, 1, 1]
Generation:  1500 Best_Fitness:  1 Individual:  [3, 2, 3, 3, 1, 1]
Generation:  2000 Best_Fitness:  1 Individual:  [3, 2, 3, 3, 1, 1]
Generation:  2500 Best_Fitness:  1 Individual:  [3, 2, 3, 3, 1, 1]
Generation:  3000 Best_Fitness:  1 Individual:  [3, 2, 3, 3, 1, 1]
Using  3  colors : 
Generation:  3000 Best_Fitness:  1 Individual:  [3, 2, 3, 3, 1, 1]





In [9]:
print(is_coloreable)

False


In [10]:
edges = []
for u in range(g1.shape[0]):
    for v in range(u, g1.shape[0]):
        if u == v:
            continue
        edges.append((u,v))

In [11]:
Backtrack3Coloreable.ThreeColorable(6, edges)

False

In [12]:
_, g2 = Generador.ConnexGraphGenerator(6)

In [13]:
edges = []
for u in range(g1.shape[0]):
    for v in range(u, g1.shape[0]):
        if u == v:
            continue
        edges.append((u,v))
Backtrack3Coloreable.ThreeColorable(6, edges)

False

In [14]:
GeneticColor.genetic_coloro(g2)

Generation:  500 Best_Fitness:  1 Individual:  [3, 2, 1, 1, 3, 2]
Generation:  1000 Best_Fitness:  1 Individual:  [3, 2, 1, 1, 3, 2]
Generation:  1500 Best_Fitness:  1 Individual:  [3, 2, 1, 1, 3, 2]
Generation:  2000 Best_Fitness:  1 Individual:  [3, 2, 1, 1, 3, 2]
Generation:  2500 Best_Fitness:  1 Individual:  [3, 2, 1, 1, 3, 2]
Generation:  3000 Best_Fitness:  1 Individual:  [3, 2, 1, 1, 3, 2]
Using  3  colors : 
Generation:  3000 Best_Fitness:  1 Individual:  [3, 2, 1, 1, 3, 2]





False

In [15]:
_, g3 = Generador.ConnexGraphGenerator(4)
g3

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [21]:
edges = []
for u in range(g3.shape[0]):
    for v in range(u, g3.shape[0]):
        if u == v:
            continue
        edges.append((u,v))
Backtrack3Coloreable.ThreeColorable(4, edges)

False

In [19]:
GeneticColor.genetic_coloro(g3)

Using  3  colors : 
Generation:  1 Best_Fitness:  0 Individual:  [3, 1, 2, 2]





True

In [24]:
new_n, edges_trans = Reduction.Reduction(4,edges)

In [25]:
z = np.zeros((new_n,new_n))
for u,v in edges_trans:
    z[u][v] = z[v][u] = 1
z

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [ ]:
GeneticCubic.genetic_algo(z)